name: Generar y guardar saludo.txt

on:
  push:
    branches: [main]

jobs:
  generar-archivo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Crear archivo de saludo
        run: echo "hola mundo" > saludo.txt

      - name: Mostrar el contenido en consola
        run: cat saludo.txt

      - name: Guardar archivo como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: saludo
          path: saludo.txt
