name: Update README on Push

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add line to README.md
        run: |
          echo "Nueva línea añadida automáticamente el $(date +'%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Commit and push README.md update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md automatically [skip ci]" || echo "No changes to commit"
          git push
